### ISSUE TITLE
Java noob

### ISSUE THREAD

**Issue by nateflanders** [usefulcoin/bitmexbot#1]
Having issues getting the script running and adding my API keys. 

Any clearer install to config instructions available by chance? 

one of the many errors i'm running in to: 

`node bitmexbot.js
(node:3612) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at new Hmac (internal/crypto/hash.js:88:11)
    at Object.createHmac (crypto.js:133:10)
    at makerestapirequest (/home/toor/bitmexbot/node_methods/makerestapirequest.js:28:26)
    at /home/toor/bitmexbot/bitmexbot.js:66:29
    at Object.<anonymous> (/home/toor/bitmexbot/bitmexbot.js:136:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:3612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

TIA

**Comment by munair** [comment]
Hi Nate:

Did you create the _**bitmexaccounts**_ file and also create the required environment variables?

Munair

**Comment by nateflanders** [comment]
@munair ah, no I did not. 

Any quick reference instructions for those mentioned steps?

**Comment by munair** [comment]
Take a look at the README.md file.

If it still isn’t apparent I will provide some more detailed instructions.

**Comment by nateflanders** [comment]
@munair went through, having issues creating the dotfile, ultimately roadblocking me from creating env variables

**Comment by munair** [comment]
hi @nateflanders ... apologies for the delayed response. i was traveling. can you send me what you've created?
